TASK parameter added

diff --git a/mount/run b/mount/run
--- a/mount/run
+++ b/mount/run
@@ -7,6 +7,11 @@ if [ -z "${IMAGE}" ]; then
   exit 1
 fi
 
+if [ -z "${TASK}" ]; then
+  printf "ERROR: The variable \$TASK should be set in the environment\n\n" 2>&1
+  exit 1
+fi
+
 if [ -d "/build" ]; then
   docker build -t ${IMAGE} /build
 fi
